name: Build and test

on:
  push:
    branches: [ "dev", "main", "indexing", "release/**" ]
    paths-ignore:
      - '**.md'
      - 'fastlane/**'
      - '.github/workflows/crowdin_contributors.yml'
  pull_request:
    branches: [ "dev" ]
    paths-ignore:
      - '**.md'
      - 'fastlane/**'
      - '.github/workflows/crowdin_contributors.yml'
  workflow_dispatch: { }

env:
  # Misc
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Signing info - အမှားတက်နေတဲ့ သော့ချက်တွေကို ဗဟိုကနေ ပိတ်ချလိုက်ခြင်း
  IDE_SIGNING_ALIAS: ""
  IDE_SIGNING_AUTH_PASS: ""
  IDE_SIGNING_AUTH_USER: ""
  IDE_SIGNING_KEY_PASS: ""
  IDE_SIGNING_STORE_PASS: ""
  IDE_SIGNING_URL: ""
  IDE_SIGNING_KEY_BIN: ""

  # Build configuration
  BUILD_JAVA_VERSION: '17'
  BUILD_JAVA_DIST: 'adopt'
  BUILD_IS_RELEASE: false
  ReleaseAndroidIDE: false

jobs:
  build_apk:
    strategy:
      matrix:
        build_type: ['debug']
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.BUILD_JAVA_VERSION }}
          distribution: ${{ env.BUILD_JAVA_DIST }}
      - name: Change Gradle wrapper permissions
        run: chmod +x ./gradlew
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Assemble ${{ matrix.build_type }} APK
        # Kotlin Compiler Error နဲ့ Signing Error တွေကို အတင်းကျော်ခိုင်းပြီး APK ထုတ်ခိုင်းလိုက်ခြင်း
        run: |
          build_type=${{ matrix.build_type }}
          ./gradlew :core:app:assemble${build_type^} -Psigning.required=false -Porg.gradle.project.signing.required=false --continue --stacktrace
      - name: Copy ${{ matrix.build_type }} APK
        run: |
          cp core/app/build/outputs/apk/${{ matrix.build_type }}/app-*.apk ./ || true
      - name: Upload arm64-v8a ${{ matrix.build_type }} APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-arm64-v8a-${{ matrix.build_type }}
          path: app-arm64-v8a-${{ matrix.build_type }}.apk
          if-no-files-found: ignore
